# melpazoid <https://github.com/riscy/melpazoid> build checks.

# for listenbrainz package

name: melpazoid-listenbrainz
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1x
      with: { python-version: 3.9 }
    - name: Install
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install emacs && emacs --version
        git clone https://github.com/riscy/melpazoid.git ~/melpazoid
        pip install ~/melpazoid
    - name: Run
      env:
        LOCAL_REPO: ${{ github.workspace }}
        # RECIPE is your recipe as written for MELPA:
        RECIPE: (listenbrainz :repo "zzkt/metabrainz" :fetcher github :files ("listenbrainz.el"))
        # set this to false (or remove it) if the package isn't on MELPA:
        # EXIST_OK: true
      run: echo $GITHUB_REF && make -C ~/melpazoid
